name: Collect GTFS Data (NYC Bus)

on:
  schedule:
    # Runs 5x/day for 7 days — adjust times as needed (UTC)
    - cron: "0 6,10,14,18,22 * * *"
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run collector
        run: |
          python fetch_realtime_gtfs.py

      - name: Commit output data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.csv || true
          git commit -m "Add new GTFS data [skip ci]" || true
          git push
